language: node_js
node_js:
  - 18

cache:
  npm: true
  directories:
    - .next/cache

branches:
  only:
    - main

before_install:
  - npm i -g vercel
  # Set up SSH key
  - echo "$DEPLOY_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

script:
  - npm run lint
  - npm run test:frontend
  - npm run test:backend
  - npm run build

deploy:
  provider: script
  script: vercel --token $VERCEL_TOKEN --prod --scope banlutas-projects --confirm
  skip_cleanup: true
  on:
    branch: main

env:
  global:
    # VERCEL_TOKEN is set in Travis CI settings
    - VERCEL_PROJECT_ID=prj_kfV8M6X7bG6dSZgYOOjmVAgAepr8
    - VERCEL_ORG_ID=banlutas-projects
