language: node_js
node_js:
  - 18

cache:
  npm: true
  directories:
    - .next/cache

branches:
  only:
    - main

before_install:
  - npm i -g vercel
  # Set up Git with token
  - git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

script:
  - npm run lint
  - npm run test:frontend
  - npm run test:backend
  - npm run build

deploy:
  provider: script
  script: vercel --token $VERCEL_TOKEN --prod --scope banlutas-projects --confirm
  skip_cleanup: true
  on:
    branch: main

env:
  global:
    # VERCEL_TOKEN and GITHUB_TOKEN are set in Travis CI settings
    - VERCEL_PROJECT_ID=prj_kfV8M6X7bG6dSZgYOOjmVAgAepr8
    - VERCEL_ORG_ID=banlutas-projects
