language: node_js
node_js:
  - 18

cache:
  directories:
    - node_modules

branches:
  only:
    - main # or your production branch

before_install:
  - npm install -g vercel

install:
  - npm ci

script:
  - npm run lint # if you have linting
  - npm run build # ensure your build succeeds

deploy:
  provider: script
  script: vercel --token $VERCEL_TOKEN --prod
  skip_cleanup: true
  on:
    branch: main # or your production branch

notifications:
  email:
    on_success: change
    on_failure: always
