language: node_js
node_js:
  - 18

cache:
  npm: true
  directories:
    - .next/cache

branches:
  only:
    - main

before_install:
  - npm i -g vercel

script:
  - npm run ci

deploy:
  provider: script
  script: vercel --token $VERCEL_TOKEN --prod --scope banlutas-projects --confirm
  skip_cleanup: true
  on:
    branch: main

env:
  global:
    - secure: "YOUR_ENCRYPTED_VERCEL_TOKEN"
    - VERCEL_PROJECT_ID=prj_kfV8M6X7bG6dSZgYOOjmVAgAepr8
    - VERCEL_ORG_ID=banlutas-projects
