apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-advanced-config
  namespace: logging
  labels:
    app: agrismart
    component: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/agrismart-*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      watch false
    </filter>

    # Filter out DEBUG logs in production
    <filter kubernetes.**>
      @type grep
      <exclude>
        key log
        pattern /^\s*DEBUG/
      </exclude>
    </filter>

    # Add parsing for structured logs
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type json
        json_parser json
      </parse>
    </filter>

    # Add service-specific filters
    <match kubernetes.var.log.containers.**agrismart-auth**.log>
      @type elasticsearch
      host elasticsearch-master
      port 9200
      logstash_format true
      logstash_prefix agrismart-auth
      <buffer>
        @type file
        path /var/log/fluentd-buffers/auth.buffer
        flush_mode interval
        flush_interval 5s
        flush_thread_count 2
        chunk_limit_size 2M
        queue_limit_length 16
      </buffer>
    </match>

    <match kubernetes.var.log.containers.**agrismart-api**.log>
      @type elasticsearch
      host elasticsearch-master
      port 9200
      logstash_format true
      logstash_prefix agrismart-api
      <buffer>
        @type file
        path /var/log/fluentd-buffers/api.buffer
        flush_mode interval
        flush_interval 5s
        flush_thread_count 2
        chunk_limit_size 2M
        queue_limit_length 16
      </buffer>
    </match>

    <match kubernetes.var.log.containers.**>
      @type elasticsearch
      host elasticsearch-master
      port 9200
      logstash_format true
      logstash_prefix agrismart
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_interval 5s
        retry_forever false
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
